---
name: flutter_versionone
description: Version One app for CNC Software
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  flutter_html: ^1.0.2
  dio: ^3.0.10
  flutter_secure_storage: ^3.3.5
  get: ^3.16.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    -
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
        - asset: assets/fonts/NotoSans-Light.ttf
        - asset: assets/fonts/NotoSans-LightItalic.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
